### ISSUE TITLE
Center title of empty content component

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#1401]
The title of the empty content component lacks padding and would look better when centered, I think.

This is how it currently looks for the search popover:
![Screenshot_2020-09-14 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/93064627-09413c00-f678-11ea-884a-b02a616378db.png)

I propose to change it to this:
![Screenshot_2020-09-14 Aufgaben - Nextcloud(1)](https://user-images.githubusercontent.com/2496460/93064699-1d853900-f678-11ea-81a1-0fdd39a54dfc.png)

```css
.empty-content__title {
    text-align: center;
    padding: 0 10px;
}
```
