### ISSUE TITLE
AppContent: no "fixed" element possible

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-vue#366]
I want to add a button to the `AppContent` which should be at a fixed position. Therefore, I'm using the CSS style `position: fixed` on that button. However, the element isn't shown fixed in the app. Instead it scrolls with the content, i.e. it behaves like `position: absolute`.

I tried to debug this issue and found out that the following line causes this behavior:

https://github.com/nextcloud/nextcloud-vue/blob/e2ea6704327bd3de9d78bb5ff52f7441e37fbd5d/src/components/AppContent/AppContent.vue#L90

If I remove this or deactivate this (e.g. with `#app-content { will-change: auto !important; }`), the behavior of my fixed element is as expected.

I've tested with Firefox 60.6.1esr and Chromium 73.0.3683.75 (Debian stable). Strange, hmm?

The easiest solution would be to remove that `will-change`, since it's just an optimization aspect. But maybe there is another solution to fix this?

**Comment by skjnldsv** [comment]
@korelstar did you set the top value of the fixed element?
This is a css requirement for it to work :)

**Comment by korelstar** [comment]
I'm using `bottom` instead, since it should be at the bottom of the window. Please see https://github.com/nextcloud/notes/blob/vue/src/Note.vue for details.

Here are the most relevant parts:

```
        <AppContent>
                <div>
                        [..]
                        <span class="action-buttons">
                                <button class="icon-details btn-sidebar" @click="onToggleSidebar" />
                                <button class="icon-fullscreen btn-fullscreen" @click="onToggleDistractionFree" />
                        </span>
                </div>
        </AppContent>
```

and the style:
```
.action-buttons {
        position: fixed;
        bottom: 4px;
        right: 20px;
        z-index: 2000;
}
```

**Comment by skjnldsv** [comment]
@korelstar works here:

``` css
.action-buttons[data-v-c28c672a] {
	position: sticky;
	bottom: 5px;
	left: 100%;
	z-index: 2000;
	display: flex;
	justify-content: space-around;
	width: 100px;
}
.action-buttons button[data-v-c28c672a] {
	padding: 14px;
	width: 44px;
	height: 44px;
	margin: 0;
}
```
![Capture d’écran_2019-04-29_10-34-35](https://user-images.githubusercontent.com/14975046/56884550-7431a900-6a6a-11e9-8b84-03866923d5f5.png)
