### ISSUE TITLE
`NcDateTimePicker` popover too small

### ISSUE THREAD

**Issue by susnux** [nextcloud/nextcloud-vue#3815]
The width of the popover is too low, so the "next"-button is clipped:

![](https://user-images.githubusercontent.com/1855448/220948378-a7fb7f7a-4524-4754-8f83-f59103a866f9.png)

---

This seems to be cause by
```css
.mx-datepicker-main .mx-calendar {
  width: 264px;
}
```

Settings this to following fixes the issue
```css
.mx-datepicker-main .mx-calendar {
  width: fit-content;
}
```
